kind: Service                             
apiVersion: v1
metadata:
  name: akhilmanoj
  labels:
    app: akhilmanoj
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: akhilmanoj                    
  type: LoadBalancer                   